alter table public.profiles
drop column if exists country;

with source_regions(name) as (
  values
    ('Afghanistan'),
    ('Albania'),
    ('Angola'),
    ('Argentina'),
    ('Armenia'),
    ('Australia'),
    ('Austria'),
    ('Azerbaijan'),
    ('Bahamas'),
    ('Bangladesh'),
    ('Barbados'),
    ('Belarus'),
    ('Belgium'),
    ('Belize'),
    ('Benin'),
    ('Bhutan'),
    ('Bolivia (Plurinational State of)'),
    ('Bosnia and Herzegovina'),
    ('Botswana'),
    ('Brazil'),
    ('Bulgaria'),
    ('Burkina Faso'),
    ('Burundi'),
    ('Cabo Verde'),
    ('Cambodia'),
    ('Chad'),
    ('Chile'),
    ('Colombia'),
    ('Comoros'),
    ('Congo, Democratic Republic of the'),
    ('Cook Islands'),
    ('Costa Rica'),
    ('Croatia'),
    ('Curaçao'),
    ('Cyprus'),
    ('Czechia'),
    ('Côte d''Ivoire'),
    ('Denmark'),
    ('Djibouti'),
    ('Dominican Republic'),
    ('Ecuador'),
    ('Egypt'),
    ('El Salvador'),
    ('Estonia'),
    ('Eswatini'),
    ('Ethiopia'),
    ('Fiji'),
    ('Finland'),
    ('France'),
    ('Gambia'),
    ('Georgia'),
    ('Germany'),
    ('Ghana'),
    ('Gibraltar'),
    ('Greece'),
    ('Guatemala'),
    ('Guinea'),
    ('Guinea-Bissau'),
    ('Guyana'),
    ('Honduras'),
    ('Hong Kong, China'),
    ('Hungary'),
    ('Iceland'),
    ('India'),
    ('Indonesia'),
    ('Ireland'),
    ('Israel'),
    ('Italy'),
    ('Jordan'),
    ('Kazakhstan'),
    ('Kenya'),
    ('Kiribati'),
    ('Lao People''s Democratic Republic'),
    ('Latvia'),
    ('Lebanon'),
    ('Lesotho'),
    ('Liberia'),
    ('Lithuania'),
    ('Luxembourg'),
    ('Macao, China'),
    ('Madagascar'),
    ('Malaysia'),
    ('Maldives'),
    ('Mali'),
    ('Malta'),
    ('Marshall Islands'),
    ('Mauritius'),
    ('Mexico'),
    ('Mongolia'),
    ('Mozambique'),
    ('Myanmar'),
    ('Namibia'),
    ('Nepal'),
    ('Netherlands'),
    ('Niger'),
    ('Nigeria'),
    ('Norway'),
    ('Pakistan'),
    ('Palau'),
    ('Palestine (State of)'),
    ('Panama'),
    ('Paraguay'),
    ('Peru'),
    ('Philippines'),
    ('Poland'),
    ('Portugal'),
    ('Puerto Rico'),
    ('Qatar'),
    ('Republic of Korea'),
    ('Republic of Moldova'),
    ('Romania'),
    ('Russian Federation'),
    ('Rwanda'),
    ('Samoa'),
    ('Sao Tome and Principe'),
    ('Saudi Arabia'),
    ('Senegal'),
    ('Serbia'),
    ('Seychelles'),
    ('Sierra Leone'),
    ('Singapore'),
    ('Slovakia'),
    ('Slovenia'),
    ('South Africa'),
    ('Spain'),
    ('Sri Lanka'),
    ('Sudan'),
    ('Suriname'),
    ('Sweden'),
    ('Switzerland'),
    ('Tanzania, United Republic of'),
    ('Thailand'),
    ('Timor-Leste'),
    ('Togo'),
    ('Tokelau'),
    ('Tonga'),
    ('Trinidad and Tobago'),
    ('Tunisia'),
    ('Türkiye'),
    ('Uganda'),
    ('Ukraine'),
    ('United Kingdom of Great Britain and Northern Ireland'),
    ('United States of America'),
    ('Uruguay'),
    ('Uzbekistan'),
    ('Venezuela (Bolivarian Republic of)'),
    ('Viet Nam'),
    ('Wallis and Futuna'),
    ('Zambia'),
    ('Zimbabwe')
)
insert into public.regions (name)
select sr.name
from source_regions sr
where not exists (
  select 1 from public.regions r where lower(r.name) = lower(sr.name)
);
