/**
 * DuckDB schema for the UNMAPPED app.
 *
 * Translated from the legacy Supabase migrations under
 * `frontend/supabase/migrations/`. Differences:
 *   - No RLS / Postgres roles (DuckDB doesn't have them). Access control
 *     happens in server functions via the session cookie.
 *   - UUIDs are stored as TEXT (generated by `crypto.randomUUID()` in app code).
 *   - No triggers (`updated_at` is set explicitly by app code).
 *   - The Supabase auth.users table is replaced with our own `users` + `sessions`.
 *   - Enums become plain TEXT with CHECK constraints (simpler to evolve).
 *
 * The full block runs inside a single `BEGIN` ... `COMMIT` so partially
 * created schemas don't get persisted.
 */
export const SCHEMA_SQL = /* sql */ `
BEGIN TRANSACTION;

CREATE TABLE IF NOT EXISTS users (
  id TEXT PRIMARY KEY,
  email TEXT NOT NULL UNIQUE,
  password_hash TEXT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT current_timestamp
);

CREATE TABLE IF NOT EXISTS sessions (
  token TEXT PRIMARY KEY,
  user_id TEXT NOT NULL,
  expires_at TIMESTAMP NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT current_timestamp
);

CREATE TABLE IF NOT EXISTS user_roles (
  id TEXT PRIMARY KEY,
  user_id TEXT NOT NULL,
  role TEXT NOT NULL CHECK (role IN ('seeker','ngo','admin')),
  created_at TIMESTAMP NOT NULL DEFAULT current_timestamp,
  UNIQUE (user_id, role)
);

CREATE TABLE IF NOT EXISTS regions (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  country_code TEXT,
  created_at TIMESTAMP NOT NULL DEFAULT current_timestamp
);

CREATE TABLE IF NOT EXISTS languages (
  code TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  native_name TEXT NOT NULL,
  script TEXT NOT NULL DEFAULT 'Latn',
  direction TEXT NOT NULL DEFAULT 'ltr' CHECK (direction IN ('ltr','rtl')),
  is_active BOOLEAN NOT NULL DEFAULT true,
  sort_order INT NOT NULL DEFAULT 0,
  created_at TIMESTAMP NOT NULL DEFAULT current_timestamp
);

CREATE TABLE IF NOT EXISTS profiles (
  id TEXT PRIMARY KEY,
  full_name TEXT,
  language TEXT DEFAULT 'en',
  region_id TEXT,
  region TEXT,
  bio TEXT,
  sex TEXT,
  salary_importance SMALLINT,
  age INTEGER,
  created_at TIMESTAMP NOT NULL DEFAULT current_timestamp,
  updated_at TIMESTAMP NOT NULL DEFAULT current_timestamp
);

CREATE TABLE IF NOT EXISTS skills (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL UNIQUE,
  category TEXT,
  created_at TIMESTAMP NOT NULL DEFAULT current_timestamp
);

CREATE TABLE IF NOT EXISTS user_skills (
  id TEXT PRIMARY KEY,
  user_id TEXT NOT NULL,
  skill_id TEXT NOT NULL,
  proficiency TEXT CHECK (proficiency IS NULL OR proficiency IN ('beginner','intermediate','advanced','expert')),
  source TEXT CHECK (source IS NULL OR source IN ('chat','manual','imported')),
  llm_level TEXT,
  user_quote TEXT,
  created_at TIMESTAMP NOT NULL DEFAULT current_timestamp,
  UNIQUE (user_id, skill_id)
);

CREATE TABLE IF NOT EXISTS chat_conversations (
  id TEXT PRIMARY KEY,
  user_id TEXT NOT NULL,
  title TEXT,
  created_at TIMESTAMP NOT NULL DEFAULT current_timestamp
);

CREATE TABLE IF NOT EXISTS chat_messages (
  id TEXT PRIMARY KEY,
  conversation_id TEXT NOT NULL,
  role TEXT NOT NULL CHECK (role IN ('user','assistant','system')),
  content TEXT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT current_timestamp
);

COMMIT;
`;

/**
 * One-time seed data — only inserted when the corresponding table is empty.
 * Each entry is a (countSql, insertSql) pair. We deliberately don't put this
 * inside a single transaction because each seed is independent.
 */
export const SEEDS: Array<{ countSql: string; insertSql: string }> = [
  {
    countSql: "SELECT COUNT(*) AS n FROM languages",
    insertSql: /* sql */ `
INSERT INTO languages (code, name, native_name, script, direction, sort_order) VALUES
  ('de', 'German',    'Deutsch',    'Latn', 'ltr', 10),
  ('en', 'English',   'English',    'Latn', 'ltr', 20),
  ('fr', 'French',    'Français',   'Latn', 'ltr', 30),
  ('ar', 'Arabic',    'العربية',     'Arab', 'rtl', 40),
  ('es', 'Spanish',   'Español',    'Latn', 'ltr', 50),
  ('it', 'Italian',   'Italiano',   'Latn', 'ltr', 60),
  ('pt', 'Portuguese','Português',  'Latn', 'ltr', 70),
  ('nl', 'Dutch',     'Nederlands', 'Latn', 'ltr', 80),
  ('pl', 'Polish',    'Polski',     'Latn', 'ltr', 90),
  ('tr', 'Turkish',   'Türkçe',     'Latn', 'ltr', 100),
  ('hi', 'Hindi',     'हिन्दी',         'Deva', 'ltr', 110),
  ('ur', 'Urdu',      'اردو',        'Arab', 'rtl', 120),
  ('bn', 'Bengali',   'বাংলা',         'Beng', 'ltr', 130),
  ('sw', 'Swahili',   'Kiswahili',  'Latn', 'ltr', 140),
  ('uk', 'Ukrainian', 'Українська', 'Cyrl', 'ltr', 150),
  ('ru', 'Russian',   'Русский',    'Cyrl', 'ltr', 160),
  ('zh', 'Chinese',   '中文',        'Hans', 'ltr', 170),
  ('ja', 'Japanese',  '日本語',      'Jpan', 'ltr', 180),
  ('ko', 'Korean',    '한국어',       'Kore', 'ltr', 190);
`,
  },
];

/**
 * Region seed — kept separate because there are ~150 entries and they're only
 * needed when the regions table is empty. Format: [name, ISO-3 code].
 * Mirrors `20260426053000_remove_country_and_seed_regions.sql`
 * + `20260426080000_populate_region_country_codes.sql`.
 */
export const REGION_SEED: Array<[string, string]> = [
  ["Afghanistan", "AFG"],
  ["Albania", "ALB"],
  ["Angola", "AGO"],
  ["Argentina", "ARG"],
  ["Armenia", "ARM"],
  ["Australia", "AUS"],
  ["Austria", "AUT"],
  ["Azerbaijan", "AZE"],
  ["Bahamas", "BHS"],
  ["Bangladesh", "BGD"],
  ["Barbados", "BRB"],
  ["Belarus", "BLR"],
  ["Belgium", "BEL"],
  ["Belize", "BLZ"],
  ["Benin", "BEN"],
  ["Bhutan", "BTN"],
  ["Bolivia (Plurinational State of)", "BOL"],
  ["Bosnia and Herzegovina", "BIH"],
  ["Botswana", "BWA"],
  ["Brazil", "BRA"],
  ["Bulgaria", "BGR"],
  ["Burkina Faso", "BFA"],
  ["Burundi", "BDI"],
  ["Cabo Verde", "CPV"],
  ["Cambodia", "KHM"],
  ["Chad", "TCD"],
  ["Chile", "CHL"],
  ["Colombia", "COL"],
  ["Comoros", "COM"],
  ["Congo, Democratic Republic of the", "COD"],
  ["Cook Islands", "COK"],
  ["Costa Rica", "CRI"],
  ["Croatia", "HRV"],
  ["Curaçao", "CUW"],
  ["Cyprus", "CYP"],
  ["Czechia", "CZE"],
  ["Côte d'Ivoire", "CIV"],
  ["Denmark", "DNK"],
  ["Djibouti", "DJI"],
  ["Dominican Republic", "DOM"],
  ["Ecuador", "ECU"],
  ["Egypt", "EGY"],
  ["El Salvador", "SLV"],
  ["Estonia", "EST"],
  ["Eswatini", "SWZ"],
  ["Ethiopia", "ETH"],
  ["Fiji", "FJI"],
  ["Finland", "FIN"],
  ["France", "FRA"],
  ["Gambia", "GMB"],
  ["Georgia", "GEO"],
  ["Germany", "DEU"],
  ["Ghana", "GHA"],
  ["Gibraltar", "GIB"],
  ["Greece", "GRC"],
  ["Guatemala", "GTM"],
  ["Guinea", "GIN"],
  ["Guinea-Bissau", "GNB"],
  ["Guyana", "GUY"],
  ["Honduras", "HND"],
  ["Hong Kong, China", "HKG"],
  ["Hungary", "HUN"],
  ["Iceland", "ISL"],
  ["India", "IND"],
  ["Indonesia", "IDN"],
  ["Ireland", "IRL"],
  ["Israel", "ISR"],
  ["Italy", "ITA"],
  ["Jordan", "JOR"],
  ["Kazakhstan", "KAZ"],
  ["Kenya", "KEN"],
  ["Kiribati", "KIR"],
  ["Lao People's Democratic Republic", "LAO"],
  ["Latvia", "LVA"],
  ["Lebanon", "LBN"],
  ["Lesotho", "LSO"],
  ["Liberia", "LBR"],
  ["Lithuania", "LTU"],
  ["Luxembourg", "LUX"],
  ["Macao, China", "MAC"],
  ["Madagascar", "MDG"],
  ["Malaysia", "MYS"],
  ["Maldives", "MDV"],
  ["Mali", "MLI"],
  ["Malta", "MLT"],
  ["Marshall Islands", "MHL"],
  ["Mauritius", "MUS"],
  ["Mexico", "MEX"],
  ["Mongolia", "MNG"],
  ["Mozambique", "MOZ"],
  ["Myanmar", "MMR"],
  ["Namibia", "NAM"],
  ["Nepal", "NPL"],
  ["Netherlands", "NLD"],
  ["Niger", "NER"],
  ["Nigeria", "NGA"],
  ["Norway", "NOR"],
  ["Pakistan", "PAK"],
  ["Palau", "PLW"],
  ["Palestine (State of)", "PSE"],
  ["Panama", "PAN"],
  ["Paraguay", "PRY"],
  ["Peru", "PER"],
  ["Philippines", "PHL"],
  ["Poland", "POL"],
  ["Portugal", "PRT"],
  ["Puerto Rico", "PRI"],
  ["Qatar", "QAT"],
  ["Republic of Korea", "KOR"],
  ["Republic of Moldova", "MDA"],
  ["Romania", "ROU"],
  ["Russian Federation", "RUS"],
  ["Rwanda", "RWA"],
  ["Samoa", "WSM"],
  ["Sao Tome and Principe", "STP"],
  ["Saudi Arabia", "SAU"],
  ["Senegal", "SEN"],
  ["Serbia", "SRB"],
  ["Seychelles", "SYC"],
  ["Sierra Leone", "SLE"],
  ["Singapore", "SGP"],
  ["Slovakia", "SVK"],
  ["Slovenia", "SVN"],
  ["South Africa", "ZAF"],
  ["Spain", "ESP"],
  ["Sri Lanka", "LKA"],
  ["Sudan", "SDN"],
  ["Suriname", "SUR"],
  ["Sweden", "SWE"],
  ["Switzerland", "CHE"],
  ["Tanzania, United Republic of", "TZA"],
  ["Thailand", "THA"],
  ["Timor-Leste", "TLS"],
  ["Togo", "TGO"],
  ["Tokelau", "TKL"],
  ["Tonga", "TON"],
  ["Trinidad and Tobago", "TTO"],
  ["Tunisia", "TUN"],
  ["Türkiye", "TUR"],
  ["Uganda", "UGA"],
  ["Ukraine", "UKR"],
  ["United Kingdom of Great Britain and Northern Ireland", "GBR"],
  ["United States of America", "USA"],
  ["Uruguay", "URY"],
  ["Uzbekistan", "UZB"],
  ["Venezuela (Bolivarian Republic of)", "VEN"],
  ["Viet Nam", "VNM"],
  ["Wallis and Futuna", "WLF"],
  ["Zambia", "ZMB"],
  ["Zimbabwe", "ZWE"],
];
